### PR TITLE
Only need ibc_denom to DeleteHostZoneProposal

### LINKED ISSUE #112: Delete hostzone proposal
when we delete host zone config, we don't really need all chain config information like [this](https://github.com/notional-labs/fee-abstraction/blob/00d8d5d9e6f3cbee313b700f5a1bac83dd5921bc/x/feeabs/types/proposal.pb.go#L196-L203). Instead, we just need IbcDenom of the token.
This issue is created to change from host chain config to ibc denom

### PR DESCRIPTION
**Pull request by anhductn2001**
Close #112

### CODE REVIEW

**Comment by anhductn2001** [comment]
Can you review it @GNaD13 ?

**Comment by GNaD13** [comment]
@anhductn2001 Can you recheck with the test and lint?

**Comment by anhductn2001** [comment]
I think it ready now @GNaD13

**Review by GNaD13 — APPROVED** [review]

**Comment by GNaD13** [comment]
Thank you @anhductn2001

**Pull request merged**
